
# Nombre que aparece en Github
name: Compila y Prueba la aplicación

# Cuando se ejecuta
on:
  push:
    branches: [ main ]   # al hacer push en la rama main
  workflow_dispatch:     # cuando se presione un botón en Github


jobs:
  # nombre de la tarea
  compilar-y-probar:
    
    runs-on: ubuntu-latest
    container: jchavarr/mono:latest

    steps:
      # descargue el proyecto
      - name: Descarga el proyecto
        uses: actions/checkout@v2

      # instalar .Net 3.1.x
      - name: Instala .NET SDK 3.1.x
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: '3.1.x'
          
      # compilar
      - name: Compila el programa
        run: dotnet build
        
      # instalar Xamarin
      - name: Instalar Xamarin
        run: |
          sudo apt install gnupg ca-certificates
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt update 
          sudo apt install -y mono-devel

      # ejecuta pruebas
      - name: Ejecuta pruebas
        run: dotnet test

